# basic
title:  Stephen's blog
subtitle: Just Do Hack!!!
description: 
keyword: 
favicon: favicon.ico

# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: /archives
  About: /about
  Rss: atom.xml

# avatar: img/avatar.png
# banner: img/banner.png
avatar: http://7xl0rs.com1.z0.glb.clouddn.com/avatar.png
banner: http://7xl0rs.com1.z0.glb.clouddn.com/banner.png

# social
social:
  twitter:  https://twitter.com
  weibo: http://www.weibo.com/3103316530/profile?rightmod=1&wvr=6&mod=personinfo
  github: https://github.com/stephenLYao


aboutContent: FEer / Muxi-Studio /Guitar Lover

# hexo-renderer-sass 
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false